import csv

# First define a dialect describing your tsv format. See the documentation on dialects for more information.
class TsvDialect(csv.Dialect):
    delimiter = '\t'
    lineterminator = '\n'
    # Controls when quotes should be generated by the writer and recognised by the reader.
    # It can take on any of the QUOTE_* constants (see section Module Contents) and defaults to QUOTE_MINIMAL.
    quoting = csv.QUOTE_NONE
    escapechar = None
    skipinitialspace = True
    strict = True

# you can just pass this class around, or you can register it under a name
csv.register_dialect('tsv', TsvDialect)
# Then you can walk through each line and copy to a new tsv:

# with open('../data/interactions/interactions.tsv', 'r', encoding="latin1") as src, open('../data/interactions/interactions - decreased.tsv', 'w', encoding="latin1") as res:
#     csrc = csv.reader(src, dialect='tsv')
#     cres = csv.writer(res, dialect='tsv')
#     for row in csrc:
#         newrow = row[:34].copy()
#         newrow = newrow[1:].copy()
#         cres.writerow(newrow)
#         # print(*newrow, file=res, sep='\t')


with open('../data/interactions/interactions - decreased.tsv', 'r', encoding="latin1") as fin, open('../data/interactions/interactions - decreased2.tsv', 'w', encoding="latin1") as fout:
    freader = csv.reader(fin, dialect='tsv')
    fwriter = csv.writer(fout, dialect='tsv')
    idx = 1
    for line in freader:
        line[4], line[0] = line[0], line[4] #switches position between first and last column
        del line[3] #delete fourth column
        line.insert(0, idx)
        fwriter.writerow(line)
        idx += 1

# 0   1   2   3   4  
# sourceTaxonId   sourceTaxonIds  sourceTaxonName sourceTaxonRank sourceTaxonPathNames
# 5   6   7   8   9
# sourceTaxonPathIds      sourceTaxonPathRankNames        sourceLifeStageId   sourceLifeStageName     sourceBodyPartId
# 10  11  12  13  14
# sourceBodyPartName      sourcePhysiologicalStateId      sourcePhysiologicalStateName    interactionTypeName interactionTypeId
# 15  16  17  18  19 
# targetTaxonId   targetTaxonIds  targetTaxonName targetTaxonRank targetTaxonPathNames
# 20  21  22  23  24
# targetTaxonPathIds      targetTaxonPathRankNames    targetLifeStageId       targetLifeStageName     targetBodyPartId
# 25  26  27  28  29
# targetBodyPartName      targetPhysiologicalStateId      targetPhysiologicalStateName        decimalLatitude decimalLongitude
# 30  31  32  33  34
# localityId      localityName    eventDateUnixEpoch      referenceCitation       referenceDoi
# 35  36  37  38  39
# referenceUrl    sourceCitation  sourceNamespace sourceArchiveURI        sourceDOI
# 40
# sourceLastSeenAtUnixEpoch